import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { radFishThemePlugin } from "@nmfs-radfish/vite-plugin-radfish-theme";

/**
 * RADFish Theme Configuration
 *
 * IMPORTANT: Change theme settings in ONE place:
 *   themes/noaa-theme/styles/theme.scss
 *
 * The radFishThemePlugin automatically:
 *   - Parses theme.scss and generates _uswds-generated.scss
 *   - Injects CSS variables into index.html
 *   - Updates index.html meta tags
 *   - Generates manifest.json (dev + build)
 *
 * Usage:
 *   radFishThemePlugin()                                              // Use default NOAA theme
 *   radFishThemePlugin({ theme: "noaa-theme", name: "My App" })      // With options
 *
 * Available themes (in themes/ folder):
 *   - noaa-theme: Default NOAA branding with USWDS colors
 */

export default defineConfig({
  base: "/",
  css: {
    preprocessorOptions: {
      scss: {
        includePaths: ["node_modules/@uswds/uswds/packages"],
        // Suppress USWDS deprecation warnings about global built-in functions
        // These are from USWDS using map-merge() which will be fixed in Dart Sass 3.0.0
        quietDeps: true,
      },
    },
  },
  plugins: [
    // RADFish theme plugin - provides:
    // - import.meta.env.RADFISH_* constants
    // - CSS variable injection
    // - manifest.json generation on build
    radFishThemePlugin({
      theme: "noaa-theme",
      name: "RADFish Boilerplate",
      shortName: "RADFish Boilerplate",
      description: "Offline-first fisheries data collection built with RADFish",
    }),
    react(),
    // VitePWA for service worker
    VitePWA({
      devOptions: {
        enabled: process.env.NODE_ENV === "development",
        type: "module",
      },
      registerType: "autoUpdate",
      injectRegister: null,
      strategies: "injectManifest",
      srcDir: "src",
      filename: "service-worker.js",
      // manifest.json is generated by radFishThemePlugin (dev + build)
      manifest: false,
    }),
  ],
  server: {
    open: true,
    port: 3000,
  },
  test: {
    globals: true,
    setupFiles: "./src/__tests__/setup.js",
    environment: "jsdom",
  },
});
