import fs from "fs";
import path from "path";
import * as sass from "sass";
import { getCacheDir, computeFileHash } from "./utils.js";
import { formatUswdsValue } from "./scss.js";

// Bump when the entry-SCSS generator changes shape so stale caches recompile.
export const CACHE_VERSION = 2;

/**
 * Check if USWDS needs recompilation based on cache
 */
export function needsRecompilation(cacheDir, tokensPath) {
  const cachePath = path.join(cacheDir, ".uswds-cache.json");
  const cssPath = path.join(cacheDir, "uswds-precompiled.css");

  // Need recompilation if cache or CSS doesn't exist
  if (!fs.existsSync(cachePath) || !fs.existsSync(cssPath)) {
    return true;
  }

  try {
    const cache = JSON.parse(fs.readFileSync(cachePath, "utf-8"));
    if (cache.cacheVersion !== CACHE_VERSION) return true;
    return cache.tokensHash !== computeFileHash(tokensPath);
  } catch {
    return true;
  }
}

/**
 * Generate SCSS entry file content for USWDS compilation
 * @param {Object} uswdsTokens - Parsed variables from SCSS file
 * @param {boolean} isUswdsConfig - If true, variables use USWDS format as-is. If false (legacy), apply transformation
 * @param {Object} [options]
 * @param {string} [options.base="/"] - Vite base URL, prefixed onto USWDS asset paths
 */
export function generateUswdsEntryScss(uswdsTokens, isUswdsConfig = false, options = {}) {
  const { base = "/" } = options;
  // Strip trailing slash so we can append /uswds-img without doubling up.
  // A bare "/" base becomes "" — paths become "/uswds-img" not "//uswds-img".
  const basePrefix = base.replace(/\/$/, "");

  // Build USWDS @use statement with all token variables
  const tokenLines = Object.entries(uswdsTokens).map(([key, value]) => {
    let uswdsKey;

    if (isUswdsConfig) {
      // New approach: uswds-config.scss variables are already in USWDS format
      // Use them as-is (e.g., "themeColorPrimary" → "$theme-color-primary")
      const kebabKey = key.replace(/([A-Z])/g, "-$1").toLowerCase();
      uswdsKey = kebabKey;
    } else {
      // Legacy approach: theme.scss variables are auto-transformed
      // Convert camelCase to kebab-case for USWDS format
      const kebabKey = key.replace(/([A-Z])/g, "-$1").toLowerCase();
      // Add theme-color- prefix for backward compatibility
      uswdsKey = `theme-color-${kebabKey}`;
    }

    // Format value: hex colors unquoted, token names quoted
    const formattedValue = formatUswdsValue(value);
    return `  $${uswdsKey}: ${formattedValue}`;
  });

  // Only inject our defaults if the consumer's uswds-config.scss hasn't already
  // configured them — @use ... with (...) errors on duplicate keys.
  const hasImagePath = isUswdsConfig && "themeImagePath" in uswdsTokens;
  const hasFontPath = isUswdsConfig && "themeFontPath" in uswdsTokens;
  const hasShowNotifications = isUswdsConfig && "themeShowNotifications" in uswdsTokens;

  const extraLines = [];
  if (!hasImagePath) {
    extraLines.push(`  $theme-image-path: "${basePrefix}/uswds-img"`);
  }
  if (!hasFontPath) {
    extraLines.push(`  $theme-font-path: "${basePrefix}/uswds-fonts"`);
  }
  if (!hasShowNotifications) {
    extraLines.push(`  $theme-show-notifications: false`);
  }

  const allLines = [...tokenLines, ...extraLines].join(",\n");

  return `/**
 * AUTO-GENERATED USWDS Entry Point
 * Generated by RADFish theme plugin for sass.compile()
 *
 * DO NOT EDIT MANUALLY - changes will be overwritten
 */

@use "uswds-core" with (
${allLines}
);

@forward "uswds";
`;
}

/**
 * Pre-compile USWDS with theme tokens to a static CSS file
 * @param {string} themeDir - Theme directory path
 * @param {string} themeName - Theme name for cache
 * @param {Object} uswdsTokens - Parsed SCSS variables
 * @param {boolean} isUswdsConfig - Whether tokens come from uswds-config.scss (new) or theme.scss (legacy)
 * @param {Object} [options]
 * @param {string} [options.base="/"] - Vite base URL, prefixed onto USWDS asset paths
 */
export function precompileUswds(themeDir, themeName, uswdsTokens, isUswdsConfig = false, options = {}) {
  const cacheDir = getCacheDir(themeName);
  const entryPath = path.join(cacheDir, "_uswds-entry.scss");
  const outputPath = path.join(cacheDir, "uswds-precompiled.css");
  const uswdsConfigPath = path.join(themeDir, "styles", "uswds-config.scss");
  const tokensPath = isUswdsConfig ? uswdsConfigPath : path.join(themeDir, "styles", "theme.scss");

  // Ensure cache directory exists
  if (!fs.existsSync(cacheDir)) {
    fs.mkdirSync(cacheDir, { recursive: true });
  }

  console.log("[radfish-theme] Pre-compiling USWDS...");
  const startTime = Date.now();

  // Generate entry SCSS with tokens (pass isUswdsConfig flag for conditional transformation)
  const entryContent = generateUswdsEntryScss(uswdsTokens, isUswdsConfig, options);
  fs.writeFileSync(entryPath, entryContent);

  // Compile with sass
  const result = sass.compile(entryPath, {
    loadPaths: [path.join(process.cwd(), "node_modules/@uswds/uswds/packages")],
    style: "compressed",
    quietDeps: true,
  });

  fs.writeFileSync(outputPath, result.css);

  // Save cache manifest
  const cacheData = {
    tokensHash: computeFileHash(tokensPath),
    cacheVersion: CACHE_VERSION,
    compiledAt: new Date().toISOString(),
  };
  fs.writeFileSync(
    path.join(cacheDir, ".uswds-cache.json"),
    JSON.stringify(cacheData, null, 2)
  );

  const elapsed = Date.now() - startTime;
  console.log(`[radfish-theme] USWDS pre-compiled in ${elapsed}ms: ${outputPath}`);
}

/**
 * Pre-compile theme SCSS file (theme.scss) to CSS
 */
export function precompileThemeScss(themeDir, themeName) {
  const cacheDir = getCacheDir(themeName);
  const stylesDir = path.join(themeDir, "styles");

  // Ensure cache directory exists
  if (!fs.existsSync(cacheDir)) {
    fs.mkdirSync(cacheDir, { recursive: true });
  }

  const inputPath = path.join(stylesDir, "theme.scss");
  const outputPath = path.join(cacheDir, "theme.css");

  if (fs.existsSync(inputPath)) {
    try {
      const result = sass.compile(inputPath, {
        loadPaths: [
          stylesDir,
          cacheDir,
          path.join(process.cwd(), "node_modules/@uswds/uswds/packages"),
        ],
        style: "compressed",
        quietDeps: true,
      });
      fs.writeFileSync(outputPath, result.css);
      console.log(`[radfish-theme] Compiled theme.scss -> theme.css`);
    } catch (err) {
      console.error(`[radfish-theme] Error compiling theme.scss:`, err.message);
    }
  }
}
